version: '3.4'

services:
  cleaner:
    container_name: docker-cleaner
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=Europe/Ljubljana
      - CLEAR_CONTAINERS=false
      - CLEAR_IMAGES=true
      - CLEAR_VOLUMES=true
      - CLEAR_NETWORKS=true
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/docker:/var/lib/docker"
